author: ericklemos
name: Reinos
version: 1.0
main: org.cabradati.reinos.App
api-version: 1.20
load: STARTUP
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.10
  - com.google.firebase:firebase-admin:9.2.0

commands:
  adicionar-reino:
    description: para adicionar reino
    usage: /<command>

  remover-reino:
    description: remover reino
    usage: /<command>

  adicionar-alianca:
    description: adicionar alianca ao reino
    usage: /<command>